
package sistema1;

import java.awt.GridLayout;
import java.awt.Point;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;
/**
 *
 * @author A. Rafael Notario Rodriguez
 */
public class CobrosConsulta extends javax.swing.JPanel {

    ConexionDBOriginal con2 = new ConexionDBOriginal();
    //Connection cn = con.conexion();
    JPanelConsulta JPC = new JPanelConsulta();
    Funciones fn = new Funciones();

//Dar formato dat al dateChooser    
    SimpleDateFormat formato = new SimpleDateFormat("yyyy/MM/dd");
    SimpleDateFormat formatoPrueba = new SimpleDateFormat("dd/MM/yyyy");

    String param = "";
    
    int cont=0;

    public CobrosConsulta() {
        initComponents();
        dateChooserCombo2.setDateFormat(formatoPrueba);
        dateParam2Fech.setDateFormat(formatoPrueba);
        jPanelCobros.setVisible(false);
        dateParam2Fech.setVisible(false);
        JRBEspecif.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        Cobro = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        datosConsul = new javax.swing.JMenuItem();
        BGIdExped = new javax.swing.ButtonGroup();
        BGDias = new javax.swing.ButtonGroup();
        txtBuscar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        dateParam2Fech = new datechooser.beans.DateChooserCombo();
        JRBEspecif = new javax.swing.JRadioButton();
        JRBLapso = new javax.swing.JRadioButton();
        dateChooserCombo2 = new datechooser.beans.DateChooserCombo();
        PanelMedicine = new javax.swing.JPanel();
        jPanelCobros = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtPago = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCambio = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtRecivido = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jCheckBoxBusquedAll = new javax.swing.JCheckBox();

        Cobro.setText("Realiza Cobro");
        Cobro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CobroActionPerformed(evt);
            }
        });
        jPopupMenu1.add(Cobro);
        jPopupMenu1.add(jSeparator1);

        datosConsul.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        datosConsul.setText("Ver datos de consulta");
        datosConsul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datosConsulActionPerformed(evt);
            }
        });
        jPopupMenu1.add(datosConsul);

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(910, 660));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBuscar.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 80, 40));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/search.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 50, 50));

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setComponentPopupMenu(jPopupMenu1);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 430, 290));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("HISTORIAL DE CONSULTAS");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 30));

        dateParam2Fech.setCalendarPreferredSize(new java.awt.Dimension(340, 230));
        dateParam2Fech.setFieldFont(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13));
        add(dateParam2Fech, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 140, 40));

        BGIdExped.add(JRBEspecif);
        JRBEspecif.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        JRBEspecif.setText("DIA ESPECIFICO");
        JRBEspecif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRBEspecifActionPerformed(evt);
            }
        });
        add(JRBEspecif, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 160, 30));

        BGIdExped.add(JRBLapso);
        JRBLapso.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        JRBLapso.setText("LAPSO DE DIAS");
        JRBLapso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRBLapsoActionPerformed(evt);
            }
        });
        add(JRBLapso, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 150, 30));

        dateChooserCombo2.setCalendarPreferredSize(new java.awt.Dimension(340, 230));
        dateChooserCombo2.setFieldFont(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 13));
        add(dateChooserCombo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 140, 40));

        PanelMedicine.setPreferredSize(new java.awt.Dimension(455, 660));
        PanelMedicine.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(PanelMedicine, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 460, -1));

        jPanelCobros.setBackground(new java.awt.Color(245, 244, 243));
        jPanelCobros.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("REALIZAR COBRO");
        jPanelCobros.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("PAGAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanelCobros.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 90, 40));

        txtPago.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPago.setForeground(new java.awt.Color(0, 0, 204));
        jPanelCobros.add(txtPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 100, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel8.setText("CANTIDAD A COBRAR $");
        jPanelCobros.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 150, 40));

        txtCambio.setBackground(new java.awt.Color(245, 244, 243));
        txtCambio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCambio.setForeground(new java.awt.Color(0, 102, 51));
        jPanelCobros.add(txtCambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 100, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel9.setText("MONTO RECIBIDO $:");
        jPanelCobros.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 120, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel10.setText("CAMBIO:");
        jPanelCobros.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 80, 40));

        txtRecivido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtRecivido.setForeground(new java.awt.Color(0, 0, 204));
        txtRecivido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRecividoFocusLost(evt);
            }
        });
        jPanelCobros.add(txtRecivido, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 100, 40));

        add(jPanelCobros, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 430, 170));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Busqueda por fecha");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 250, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Expediente No.");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 160, 40));

        jCheckBoxBusquedAll.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jCheckBoxBusquedAll.setText("Ver Todas");
        jCheckBoxBusquedAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxBusquedAllActionPerformed(evt);
            }
        });
        add(jCheckBoxBusquedAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        String var = txtBuscar.getText();
        
            if(JRBEspecif.isSelected() && !var.equals("/"))
            {
                //txtBuscar.setText("");
                mostrarTabla2(var,"expedienteF1");// TODO add your handling code here:
            }
            
            if(JRBLapso.isSelected() && !var.equals("/"))
            {
                //txtBuscar.setText("");
                mostrarTabla2(var,"expedienteF2");
            }
            
            if(jCheckBoxBusquedAll.isSelected() && var.equals("/")){
              
                mostrarTabla2(var,"fecha1All");
            }

            if(jCheckBoxBusquedAll.isSelected() && dateParam2Fech.isVisible())
            {
                mostrarTabla2(var,"fecha2All");// TODO add your handling code here:
            }        
    }//GEN-LAST:event_jLabel2MouseClicked

    private void CobroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CobroActionPerformed
jPanelCobros.setVisible(true);
/*        String estado,monto,id;
        int fila = jTable1.getSelectedRow();
        String var="";
        
        if(fila >= 0)
        {
            
            id=jTable1.getValueAt(fila, 0).toString();
            estado=jTable1.getValueAt(fila, 2).toString();
            monto = jTable1.getValueAt(fila, 3).toString();
            
            if(estado.equals("Pendiente"))
                jRadioButton2.setSelected(true);
            else
                jRadioButton1.setSelected(true);
            
            txtPago.setText(monto);
        }else{
            JOptionPane.showMessageDialog(null,"Seleccione un paciente.");
        }*/
    }//GEN-LAST:event_CobroActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Connection cn = con2.conexion();
        String var=txtPago.getText();
        String estado,monto,id;
        
        
        int fila = jTable1.getSelectedRow();
        id=jTable1.getValueAt(fila, 0).toString();
        Statement st = null;

        try
        {
            st = cn.createStatement();
  
            st.executeUpdate("UPDATE t_consultas SET costo= '"+var+"',status=1 WHERE id_consultas="+id);
            JOptionPane.showMessageDialog(null, "Pago Realizado");
        }catch (Exception e)
        {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error al realizar pago");            
        }finally{
//            System.out.println( "cierra conexion a la base de datos" );    
            try {
                if(st != null) st.close();                
                if(cn !=null) cn.close();
            } catch (SQLException ex) {
                System.err.println( ex.getMessage() );    
            }
         }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void datosConsulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datosConsulActionPerformed
        int fila = jTable1.getSelectedRow();
        String var="";
        
        if(fila >= 0)
        {
            fn.limpiar(PanelMedicine);
            PanelMedicine.setVisible(true);
            
            var=jTable1.getValueAt(fila, 0).toString();
            JPC.setEnabled(true);
            JPC.setVisible(true);
            
            JPC.RealizaConsulta(var);
            JPC.ConsultaReceta(var);
            
            JPC.jLabelGuardaReceta.setVisible(false);
            JPC.jLabelLlenaTabla.setVisible(false);

            JPC.jLabelPDF.setVisible(true);
            
                        JPC.txtId_Consul.setText(var);

            PanelMedicine.setLayout(new GridLayout(1,1));
            PanelMedicine.add(JPC);
            PanelMedicine.validate();
            PanelMedicine.setVisible(true);
            PanelMedicine.setEnabled(true);
            

        }else{
            JOptionPane.showMessageDialog(null,"Seleccione un paciente.");
        }

    }//GEN-LAST:event_datosConsulActionPerformed

    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        if (evt.getClickCount() > 1)
        {
            
            
        }
/*
        Point point = evt.getPoint();
        int row = jTable1.rowAtPoint(point);
        int column = jTable1.columnAtPoint(point);
        TableModel model = jTable1.getModel();
        JOptionPane.showMessageDialog(this, model.getValueAt(row, column));
*/

    }//GEN-LAST:event_jTable1MousePressed

    private void JRBEspecifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRBEspecifActionPerformed
        if(JRBEspecif.isSelected()){
            dateParam2Fech.setVisible(false);
        }
    }//GEN-LAST:event_JRBEspecifActionPerformed

    private void JRBLapsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRBLapsoActionPerformed
        if(JRBLapso.isSelected()){
            dateParam2Fech.setVisible(true);
        }
    }//GEN-LAST:event_JRBLapsoActionPerformed

    private void txtRecividoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRecividoFocusLost
        txtCambio.setText("");
        String reciv = txtRecivido.getText(),cobro=txtPago.getText();
        if(reciv.isEmpty() || cobro.isEmpty()){
            JOptionPane.showMessageDialog(null, "Campo cantidad o monto vacios\n Verifique Por favor");
        }else{
            BigDecimal amountOne = new BigDecimal(reciv);//monto a cobrar
           BigDecimal amountTwo = new BigDecimal(cobro);//cantidad recivida
           txtCambio.setText(fn.getDifference(amountOne, amountTwo).toString());
        }
    }//GEN-LAST:event_txtRecividoFocusLost

    private void jCheckBoxBusquedAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxBusquedAllActionPerformed
            if(jCheckBoxBusquedAll.isSelected()){
                txtBuscar.setText("/");
            }
    }//GEN-LAST:event_jCheckBoxBusquedAllActionPerformed

    void mostrarTabla1(String var){
        Connection cn = con2.conexion();
        DefaultTableModel modelo = new DefaultTableModel();
        TableColumn columna;
        String consul="";

        modelo.addColumn("Consulta");
        modelo.addColumn("Expediente");
        //modelo.addColumn("Pago");
        //modelo.addColumn("Monto");
        
        jTable1.setModel(modelo);
        columna = jTable1.getColumn("Consulta");
        columna.setPreferredWidth(5);
        //if(var.equals("/"))
        //{
          //  consul = "SELECT id_Consulta, expediente, estado, monto FROM consulta";
        //}else{
            consul = "SELECT id_consultas, expediente FROM t_consultas WHERE expediente = '"+var+"'";
//            System.out.println("Consulta: "+consul);
        //}
        String datos[] =  new String[4];
        Statement st = null;
        ResultSet rs = null;
        try {
            st = cn.createStatement();
            rs = st.executeQuery(consul);
            while(rs.next()){
                datos[0] =rs.getString(1);
                datos[1] = rs.getString(2);
                modelo.addRow(datos);
            }
            jTable1.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(CobrosConsulta.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
//            System.out.println( "cierra conexion a la base de datos" );    
            try {
                if(rs != null) rs.close();               
                if(st != null) st.close();                
                if(cn !=null) cn.close();
            } catch (SQLException ex) {
//                System.err.println( ex.getMessage() );    
            }
         }
    }

    void mostrarTabla2(String var,String campo){
        Connection cn = con2.conexion();
        DefaultTableModel modelo = new DefaultTableModel();
        TableColumn columna, columna1,columna2,columna3,columna4;
        String consul="", fech1 = fn.volteaFecha(dateChooserCombo2.getText(),0),fech2 = fn.volteaFecha(dateParam2Fech.getText(),0);

        modelo.addColumn("IdConsulta");
        modelo.addColumn("Expediente");
        modelo.addColumn("Fecha");
        modelo.addColumn("Monto");
        modelo.addColumn("Status");
                
        jTable1.setModel(modelo);
        columna = jTable1.getColumn("IdConsulta");
        columna1 = jTable1.getColumn("Expediente");
        columna2 = jTable1.getColumn("Fecha");
        columna3 = jTable1.getColumn("Monto");
        columna4 = jTable1.getColumn("Status");
        
        columna.setPreferredWidth(1);
        columna1.setPreferredWidth(5);
      //  columna2.setPreferredWidth(5);
        columna3.setPreferredWidth(5);
        columna4.setPreferredWidth(1);

        if(campo.equals("expedienteF1"))
        {
            consul = "SELECT id_consultas, expediente,fecha,costo,status FROM t_consultas WHERE expediente = '"+var+"' AND fecha = '"+fech1+"'  ";
        }
        if(campo.equals("expedienteF2"))
        {
            consul = "SELECT id_consultas, expediente,fecha,costo,status FROM t_consultas WHERE expediente = '"+var+"' AND fecha BETWEEN '"+fech1+"' AND '"+fech2+"' ";
        }
        if(campo.equals("fecha1All"))
        {
            consul = "SELECT id_consultas, expediente,fecha,costo,status FROM t_consultas WHERE fecha = '"+fech1+"' ";
        }
        if(campo.equals("fecha2All"))
        {
            consul = "SELECT id_consultas, expediente,fecha,costo,status FROM t_consultas WHERE fecha BETWEEN '"+fech1+"' AND '"+fech2+"' ";            
        }
//        System.out.println("Consulta: "+consul);
        String datos[] =  new String[5];
        Statement st = null;
        ResultSet rs = null;
        try {
            st = cn.createStatement();
            rs = st.executeQuery(consul);
            while(rs.next()){
                datos[0] =rs.getString(1);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                datos[3] = rs.getString(4);
                datos[4] = rs.getString(5);
                txtPago.setText(datos[3]);
                modelo.addRow(datos);
            }
            jTable1.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(CobrosConsulta.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
//            System.out.println( "cierra conexion a la base de datos" );    
            try {
                if(rs != null) rs.close();                
                if(st != null) st.close();                
                if(cn !=null) cn.close();
            } catch (SQLException ex) {
                System.err.println( ex.getMessage() );    
            }
         }
    }     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BGDias;
    private javax.swing.ButtonGroup BGIdExped;
    private javax.swing.JMenuItem Cobro;
    private javax.swing.JRadioButton JRBEspecif;
    private javax.swing.JRadioButton JRBLapso;
    public javax.swing.JPanel PanelMedicine;
    private javax.swing.ButtonGroup buttonGroup1;
    private datechooser.beans.DateChooserCombo dateChooserCombo2;
    private datechooser.beans.DateChooserCombo dateParam2Fech;
    private javax.swing.JMenuItem datosConsul;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBoxBusquedAll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelCobros;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTable jTable1;
    public javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCambio;
    private javax.swing.JTextField txtPago;
    private javax.swing.JTextField txtRecivido;
    // End of variables declaration//GEN-END:variables
}