/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema1;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author JOGUA
 */
public class HistorConsultas extends javax.swing.JPanel {

        ConexionDBOriginal con2 = new ConexionDBOriginal();

        public HistorConsultas() {
        initComponents();
        
        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtExped = new javax.swing.JTextField();
        txtApPater = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        label = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(245, 244, 243));
        setPreferredSize(new java.awt.Dimension(455, 658));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("EXPEDIENTE:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 110, 40));
        add(txtExped, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 70, 35));
        add(txtApPater, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 220, 35));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("NOMBRE:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 70, 30));
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 150, 35));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 440, 430));

        label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/search.png"))); // NOI18N
        label.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelMouseClicked(evt);
            }
        });
        add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 50, 50));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("HISTORIAL DE CONSULTAS");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 230, 30));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 400, 10));
    }// </editor-fold>//GEN-END:initComponents

    private void labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMouseClicked
        mostrarTabla1(txtExped.getText());
        // TODO add your handling code here:
    }//GEN-LAST:event_labelMouseClicked

    void mostrarTabla1(String var){
        Connection cn = con2.conexion();
        
        DefaultTableModel modelo = new DefaultTableModel();
        TableColumn columnaId,columnaExp;
        String consul="";
        modelo.addColumn("ID");
        modelo.addColumn("EXPEDIENTE");
        modelo.addColumn("FECHA");
        
        jTable1.setModel(modelo);
        columnaId = jTable1.getColumn("ID");
        columnaExp = jTable1.getColumn("EXPEDIENTE");
        
        columnaId.setPreferredWidth(6);
        columnaExp.setPreferredWidth(7);
        
        if(var.equals("/"))
        {
            consul = "SELECT id_consultas, expediente,fecha FROM t_consultas";
        }else{
            consul = "SELECT id_consultas, expediente,fecha FROM t_consultas WHERE expediente = '"+var+"'";
//            System.out.println("Consulta: "+consul);
        }
        
        String datos[] =  new String[3];
        Statement st = null;
        ResultSet rs = null;
        try {
            st = cn.createStatement();
            rs = st.executeQuery(consul);
            while(rs.next()){
                datos[0] =rs.getString(1);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                modelo.addRow(datos);
            }
            jTable1.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(HistorConsultas.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
//                    System.out.println( "cierra conexion a la base de datos" );    
                    try {
                        if(st != null) st.close();
                        if(rs != null) rs.close();
                        if(cn != null) cn.close();
//                        if(cn !=null) cn.close();
                    } catch (SQLException ex) {
                        System.err.println( ex.getMessage() );    
                    }
                }
        
         
    }    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel label;
    public javax.swing.JTextField txtApPater;
    public javax.swing.JTextField txtExped;
    public javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
