
package sistema1;

import java.awt.GridLayout;
import java.awt.event.ComponentListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Maquina53
 */
public class LOGIN extends javax.swing.JPanel {

    

    public LOGIN() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelusuario = new javax.swing.JLabel();
        jTextFieldUusario = new javax.swing.JTextField();
        jLabelpass = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButtonIniciarsesion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1350, 640));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelusuario.setBackground(new java.awt.Color(255, 255, 255));
        jLabelusuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelusuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelusuario.setText("Usuario:");
        add(jLabelusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 250, 100, 30));

        jTextFieldUusario.setBackground(new java.awt.Color(87, 89, 88));
        jTextFieldUusario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldUusario.setForeground(new java.awt.Color(255, 255, 255));
        add(jTextFieldUusario, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 250, 210, 30));

        jLabelpass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelpass.setForeground(new java.awt.Color(255, 255, 255));
        jLabelpass.setText("Password:");
        add(jLabelpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 300, 110, 30));

        jPasswordField1.setBackground(new java.awt.Color(87, 89, 88));
        jPasswordField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(255, 255, 255));
        add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 300, 210, 30));

        jButtonIniciarsesion.setBackground(new java.awt.Color(0, 0, 204));
        jButtonIniciarsesion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonIniciarsesion.setForeground(new java.awt.Color(255, 255, 255));
        jButtonIniciarsesion.setText("Iniciar Sesion");
        jButtonIniciarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarsesionActionPerformed(evt);
            }
        });
        add(jButtonIniciarsesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 360, 170, 30));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GINECOLOGO Y OBSTETRA U.A de C.");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 410, 60));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ginecología - Obstetricia - Colposcopia");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, 490, 60));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Dr. Jorge Nuño Rubio");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 410, 60));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 330, 20, 220));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo-rafa_opt (2).png"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 280, 310));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo_azul.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 640));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIniciarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarsesionActionPerformed
        String user = jTextFieldUusario.getText();
        String pass = jPasswordField1.getText();
        if(user.equals("usuario") && pass.equals("123"))
        {
            try {
                this.setVisible(false);
                this.disable();

            } catch (Throwable ex) {
                Logger.getLogger(LOGIN.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else
        {
            JOptionPane.showMessageDialog(null,"Usuario o contraseña incorrecto");
        }

    }//GEN-LAST:event_jButtonIniciarsesionActionPerformed

    public void limpiar()
    {
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIniciarsesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelpass;
    private javax.swing.JLabel jLabelusuario;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldUusario;
    // End of variables declaration//GEN-END:variables
}
