/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pruebas;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class BusquedaPaciente1 extends javax.swing.JPanel {

    conexionDB con = new conexionDB();
    Connection cn = con.conexion();

    
    public BusquedaPaciente1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioNom = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        jRadioExp = new javax.swing.JRadioButton();
        txtConsul = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(450, 630));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(jRadioNom);
        jRadioNom.setText("Apellido");
        add(jRadioNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 100, 30));

        jLabel19.setText("Consultar por:");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        buttonGroup1.add(jRadioExp);
        jRadioExp.setText("# Expediente");
        add(jRadioExp, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, 30));
        add(txtConsul, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 170, 30));

        jButton3.setText("BUSCAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 90, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 430, 520));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String var = txtConsul.getText();
        if(var.isEmpty()){
            JOptionPane.showMessageDialog(null,"Campo vacio");
        }else{
        if(jRadioExp.isSelected()){
            mostrarTabla(txtConsul.getText());
            
        }
        if(jRadioNom.isSelected()){
            
            
        }
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    void mostrarTabla(String var){
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Expediente");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        jTable1.setModel(modelo);
        
        String consul = "SELECT expediente, nombre, paterno from paciente where materno like '%"+var+"%' ";
        
        String datos[] =  new String[3];
        Statement st;
        try {
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(consul);
            while(rs.next()){
                datos[0] =rs.getString(1);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
            
                modelo.addRow(datos);
            }
            
            jTable1.setModel(modelo);
            
        } catch (SQLException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JRadioButton jRadioExp;
    private javax.swing.JRadioButton jRadioNom;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtConsul;
    // End of variables declaration//GEN-END:variables
}
