/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pruebas;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import sistema1.Funciones;

/**
 *
 * @author JOGUA
 */
public class JPanelAltaPacientes extends javax.swing.JPanel {

    Funciones fn = new Funciones();
    conexionDB con = new conexionDB();
    public String param = "";

    public JPanelAltaPacientes() {
        initComponents();
        llenacombo();
        txtExped.setText(Integer.toString(ultimoRegistro()));
        jDateChooser1.setDate(cargafecha());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        txtExped = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtPaterno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtMaterno = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        txtDirec = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtCel = new javax.swing.JTextField();
        txtTiempo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtPareja = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        txtAbortos = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtCesareas = new javax.swing.JTextField();
        txtPartos = new javax.swing.JTextField();
        txtGestas = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanelHConsultas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 254, 255));
        setPreferredSize(new java.awt.Dimension(450, 660));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("DATOS DEL PACIENTE");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 30));

        jDateChooser1.setDateFormatString("dd/MM/yyyy");
        jDateChooser1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDateChooser1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jDateChooser1MousePressed(evt);
            }
        });
        add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 140, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("FECHA:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 50, 30));

        txtExped.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtExpedKeyPressed(evt);
            }
        });
        add(txtExped, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 60, 30));
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 110, 30));
        add(txtPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 110, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("AP MATERNO:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 90, 30));
        add(txtMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 130, 30));

        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 130, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("ESTADO CIVIL:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 100, 30));
        add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 110, 30));
        add(txtDirec, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 330, 30));
        add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 100, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("CELULAR:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 70, 30));
        add(txtCel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 90, 30));
        add(txtTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 60, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("TIEMPO:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, -1, 30));
        add(txtPareja, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 180, 30));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 140, -1));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 150, 10));
        add(txtAbortos, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 110, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("ABORTOS:");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 70, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("CESAREAS:");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 70, 30));
        add(txtCesareas, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 110, 30));
        add(txtPartos, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 80, 30));
        add(txtGestas, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 80, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("GESTAS:");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 90, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("PARTOS:");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 90, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("PAREJA:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 70, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("TELEFONO:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 90, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("DIRECCION:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 90, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("EDAD:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 80, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("AP PATERNO:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 90, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("NOMBRE:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 90, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("EXPEDIENTE:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 90, 30));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/trash32px.png"))); // NOI18N
        jLabel14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 50, 50));

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/save32x32.png"))); // NOI18N
        jLabel19.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 50, 50));

        jPanelHConsultas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanelHConsultas.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 440, 210));

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/exit.png"))); // NOI18N
        jLabel21.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelHConsultas.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 40, 40));

        add(jPanelHConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 460, 260));

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/exit.png"))); // NOI18N
        jLabel22.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 50, 50));

        jButton1.setText("PruebaT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jDateChooser1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateChooser1MouseClicked
    }//GEN-LAST:event_jDateChooser1MouseClicked

    private void jDateChooser1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateChooser1MousePressed
    }//GEN-LAST:event_jDateChooser1MousePressed

    private void txtExpedKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtExpedKeyPressed
    }//GEN-LAST:event_txtExpedKeyPressed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        Connection cn = con.conexion();
        String exped,fech,nomb,apPat,apMat,edad,civil,direc,tel,cel,pareja,tiempo,gestas,abortos,partos,cesareas,SQL="";

// Letrero de prueba        JOptionPane.showMessageDialog(null, "fecha: "+fech);
        exped = txtExped.getText();//expediente
        fech = fn.getFecha(jDateChooser1);//fecha
        nomb = txtNombre.getText();//nombre
        apPat = txtPaterno.getText();//paterno
        apMat = txtMaterno.getText();//materno
        edad=txtEdad.getText();//edad
        civil = jComboBox1.getSelectedItem().toString();//civil
        direc =txtDirec.getText();//direccion
        tel = txtTelefono.getText();//tel
        cel = txtCel.getText();//cel
        pareja = txtPareja.getText();//pareja
        tiempo = txtTiempo.getText();//tiempo
        gestas = txtGestas.getText();//gestas
        abortos = txtAbortos.getText();//abortos
        partos = txtPartos.getText();//partos
        cesareas = txtCesareas.getText();//cesareas
        
        PreparedStatement pps=null;

        if(exped.isEmpty() || nomb.isEmpty())
            JOptionPane.showMessageDialog(null,"Nombre ó Apellido vacio");
        else{
            
            if(fn.ValidaExpedienteBool(exped))
            {
                SQL="UPDATE paciente SET expediente='"+exped+"' ,fecha='"+fech+"',nombre='"+nomb+"',paterno='"+apPat+"',materno='"+apMat+"',edad='"+
                edad+"',civil='"+civil+"',direccion='"+direc+"',tel='"+tel+"',cel='"+cel+"',pareja='"+pareja+"',tiempo='"+tiempo+"',gestas='"+
                gestas+"',abortos='"+abortos+"',partos='"+partos+"',cesareas='"+cesareas+"' WHERE expediente = '"+exped+"'";
            
                PreparedStatement pstmt = null;
                try {
            //        cn.setAutoCommit(false);
                        System.out.println(SQL);
                        pstmt = cn.prepareStatement(SQL);
              //      cn.commit();

                    pstmt.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Datos guardados");
                }catch (SQLException e){
                    Logger.getLogger(JPanelAltaPacientes.class.getName()).log(Level.SEVERE, null, e);
                }finally{
                    System.out.println( "cierra conexion a la base de datos" );    
                    try {
                        if(pstmt != null) pstmt.close();
                        if(cn != null) cn.close();
//                        if(cn !=null) cn.close();
                    } catch (SQLException ex) {
                        System.err.println( ex.getMessage() );    
                    }
                }
            }//if
            else{
                SQL="INSERT INTO paciente (expediente,fecha,nombre,paterno,materno,edad,civil,direccion,tel,cel,pareja,tiempo,gestas,abortos,partos,cesareas) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";

            System.out.println(SQL);
            try {
                pps = cn.prepareStatement(SQL);
                pps.setString(1, exped);
                pps.setString(2, fech);
                pps.setString(3, nomb);
                pps.setString(4, apPat);
                pps.setString(5, apMat);
                pps.setString(6, edad);
                pps.setString(7, civil);
                pps.setString(8, direc);
                
                if(!tel.isEmpty())
                    pps.setString(9, txtTelefono.getText());
                else
                    pps.setString(9, "/");
                
                if(!cel.isEmpty())
                    pps.setString(10, txtCel.getText());
                else
                    pps.setString(10, "/");

                if(!pareja.isEmpty())
                    pps.setString(11, txtPareja.getText());
                else
                    pps.setString(11, "/");
                
                if(!tiempo.isEmpty())
                    pps.setString(12, txtEdad.getText());
                else
                    pps.setString(12, "/");
                
                if(!gestas.isEmpty())
                    pps.setString(13, txtGestas.getText());
                else
                    pps.setString(13,"/");
                
                if(!abortos.isEmpty())
                    pps.setString(14, txtAbortos.getText());
                else
                    pps.setString(14, "/");
                
                if(!partos.isEmpty())
                    pps.setString(15, txtPartos.getText());
                else
                    pps.setString(15, "/");
                
                if(!cesareas.isEmpty())
                    pps.setString(16, txtCesareas.getText());
                else
                    pps.setString(16, "/");

                pps.executeUpdate();

                JOptionPane.showMessageDialog(null, "Datos Guardados");

                limpiarCampos();

            } catch (SQLException ex) {
                Logger.getLogger(JPanelAltaPacientes.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Error durante la transaccion");
            }finally{
                System.out.println( "cierra conexion a la base de datos" );    
                try {
                    if(pps != null) pps.close();                
                    if(cn !=null) cn.close();
                    } catch (SQLException ex) {
                        System.err.println( ex.getMessage() );    
                    }
            }
        }
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        Connection cn = con.conexion();
        PreparedStatement preparedStmt = null;
        String var=txtExped.getText();
        if(!var.isEmpty()){

            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog (null, "Seguro que desea eliminar al paciente:"+var,"Borrar",dialogButton);
            if(dialogResult == JOptionPane.YES_OPTION){
            try {
            String query = "delete from paciente where expediente = '"+var+"' ";
            preparedStmt = cn.prepareStatement(query);
            preparedStmt.execute();
      
            JOptionPane.showMessageDialog(null, "Eliminado");

            limpiarCampos();

        } catch (SQLException ex) {
            Logger.getLogger(JPanelAltaPacientes.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            System.out.println("cierra conexion a la base de datos");    
            try {
                if(preparedStmt != null) preparedStmt.close();                
                if(cn !=null) cn.close();
            } catch (SQLException ex) {
                System.err.println(ex.getMessage()); 
                System.out.println("Error al cerrar la conexon");
            }//catch
        }//finally 
            } else {
                JOptionPane.showMessageDialog(null,"No se borro el Expediente:"+var);
            }

        }else
            JOptionPane.showMessageDialog(null,"no selecciono nada");
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_jLabel22MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String var = txtExped.getText();
        System.out.println("EXPED -:"+var);
        mostrarTabla2(var);
    }//GEN-LAST:event_jButton1ActionPerformed

    public void limpiarCampos(){
        txtExped.setText(Integer.toString(ultimoRegistro()));
        txtNombre.setText("");
        txtPaterno.setText("");
        txtMaterno.setText("");
        txtTelefono.setText("");
        txtCel.setText("");
        txtDirec.setText("");
        txtEdad.setText("");
        txtPareja.setText("");
        txtTiempo.setText("");
        txtAbortos.setText("");
        txtCesareas.setText("");
        txtGestas.setText("");
        txtPartos.setText("");
        txtTiempo.setText("");
//        jComboBox1.setSelectedIndex(0);
//        jDateChooser1.getDateEditor().getUiComponent().requestFocusInWindow();
        jDateChooser1.setDate(cargafecha());
        llenacombo();
    }

    private Date cargafecha(){
        //DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        Date fechaAct = new Date();
//        jDateChooser1.setDate(fechaAct);
        return fechaAct;
    }

    void llenacombo(){
        Connection cn = con.conexion();
        jComboBox1.removeAllItems();
        String consul = "SELECT estado from civil";
        int i = 1;
        Statement st = null;
        ResultSet rs = null;
        try {
            st = cn.createStatement();
            rs = st.executeQuery(consul);
            while(rs.next()){
                jComboBox1.addItem(rs.getString(i));
            }
        } catch (SQLException ex) {
            Logger.getLogger(JPanelAltaPacientes.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
                    System.out.println( "cierra conexion a la base de datos" );    
                    try {
                        if(st != null) st.close();
                        if(cn != null) cn.close();
//                        if(cn !=null) cn.close();
                    } catch (SQLException ex) {
                        System.err.println( ex.getMessage() );    
                    }
                }
    }
            
    private int ultimoRegistro(){
        Connection cn = con.conexion();
        String ultimo="";
        int num=0;
        String sql = "SELECT expediente FROM paciente";
        Statement st = null;
        ResultSet rs= null;
        
        try {
            st = cn.createStatement();
            rs = st.executeQuery(sql);
            while(rs.next())
            {
                ultimo = rs.getString(1);
            }
        } catch (SQLException ex) {
            Logger.getLogger(JPanelAltaPacientes.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
                    System.out.println( "cierra conexion a la base de datos" );    
                    try {
                        if(st != null) st.close();
                        if(cn != null) cn.close();
//                        if(cn !=null) cn.close();
                    } catch (SQLException ex) {
                        System.err.println( ex.getMessage() );    
                    }
                }
        num=Integer.parseInt(ultimo);
        
        return num+1;
    }
    
    public void mostrarTabla2(String var){
        Connection cn = con.conexion();
        DefaultTableModel modelo = new DefaultTableModel(){ 
            @Override
            public boolean isCellEditable (int fila, int columna) {
                return false;
            }
        };
        
        TableColumn columna, columna1;
        String consul = ""; 

        modelo.addColumn("Id");
        modelo.addColumn("Exp");
        modelo.addColumn("Pago");
        modelo.addColumn("Monto");
        
        jTable1.setModel(modelo);
        columna = jTable1.getColumn("Id");
        columna1 = jTable1.getColumn("Exp");
        
        columna.setPreferredWidth(5);
        columna1.setPreferredWidth(5);

        consul = "SELECT id_Consulta, expediente, estado, monto FROM consulta WHERE expediente = "+var+"";
        
        System.out.println("Consulta: "+consul);
        String datos[] =  new String[4];
        Statement st = null;
        ResultSet rs = null;
        try {
            st = cn.createStatement();
            rs = st.executeQuery(consul);
            while(rs.next()){
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                    JOptionPane.showMessageDialog(null, "tipo: "+datos[2]);
                datos[3] = rs.getString(4);

                modelo.addRow(datos);
            }
            jTable1.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(JPanelAltaPacientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }        



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    public javax.swing.JComboBox<String> jComboBox1;
    public com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelHConsultas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    public javax.swing.JTextField txtAbortos;
    public javax.swing.JTextField txtCel;
    public javax.swing.JTextField txtCesareas;
    public javax.swing.JTextField txtDirec;
    public javax.swing.JTextField txtEdad;
    public javax.swing.JTextField txtExped;
    public javax.swing.JTextField txtGestas;
    public javax.swing.JTextField txtMaterno;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtPareja;
    public javax.swing.JTextField txtPartos;
    public javax.swing.JTextField txtPaterno;
    public javax.swing.JTextField txtTelefono;
    public javax.swing.JTextField txtTiempo;
    // End of variables declaration//GEN-END:variables
}
